import { NavLink } from 'react-router-dom';
import { ArrowRight, CalendarPlus, RefreshCw, Users, Trophy, Clock3, Activity } from 'lucide-react';
import { useI18n } from '../i18n';
import { formatDate } from '../lib/format';
import type { CustomTeam, HealthStatus, InhouseMatch, Player, PowerRating, Tournament } from '../types';
interface Props { data: { players: Player[]; matches: InhouseMatch[]; health: HealthStatus | null; ratings: Record<string, PowerRating>; teams: CustomTeam[]; tournaments: Tournament[] }; loading: boolean; error: string; reload: () => Promise<void> }

export function OperationsHome({ data, loading, error, reload }: Props) {
  const { language, t } = useI18n(); const ko = language === 'ko';
  const players = data.players.filter(p => p.active);
  const today = players.filter(p => p.participating);
  const pending = data.matches.filter(m => m.status === 'READY' || m.status === 'IN_PROGRESS');
  const completed = data.matches.filter(m => m.status === 'COMPLETED');
  const ready = Boolean(data.health?.database) && !error;
  const date = new Intl.DateTimeFormat(ko ? 'ko-KR' : 'en-US', { month: 'long', day: 'numeric', weekday: 'long', timeZone: 'Asia/Seoul' }).format(new Date());
  return <>
    <div className="home-heading"><div><p className="eyebrow">CLUB OPERATIONS / {date}</p><h1>{ko ? '오늘의 내전' : 'Today’s inhouse'}</h1></div><button className="button secondary" onClick={() => void reload()} disabled={loading}><RefreshCw size={15} />{t('refresh')}</button></div>
    {error && <div className="alert" role="alert"><strong>{t('error')}</strong><span>{error}</span><button className="text-button" onClick={() => void reload()}>{t('retry')}</button></div>}
    <section className="matchday-hero"><div className="hero-copy"><p className="eyebrow">READY WHEN YOU ARE</p><h2>{ko ? <>오늘 모인 사람들로,<br />가장 균형 있는 한 판.</> : <>Your players.<br />Your next balanced match.</>}</h2><p>{ko ? '참가자를 확인하고 포지션별 전력으로 팀을 나누세요. 끝난 경기는 다음 편성의 기록이 됩니다.' : 'Check attendance, balance teams by role, and keep results for the next match.'}</p><div className="button-row"><NavLink className="button primary" to={today.length >= 10 && ready ? '/builder' : '/players'}>{today.length >= 10 ? (ko ? '오늘 팀 편성하기' : 'Build today’s teams') : (ko ? '참가자 선택하기' : 'Select participants')}<ArrowRight size={16} /></NavLink><NavLink className="text-link" to="/history">{ko ? '경기 결과 입력' : 'Record results'} →</NavLink></div></div>
      <div className="attendance-ring"><span>{ko ? '오늘 참가' : 'Playing today'}</span><strong>{loading ? '…' : today.length}<small>명</small></strong><div className="attendance-track"><i style={{ width: `${Math.min(100, today.length / 10 * 100)}%` }} /></div><p>{today.length < 10 ? (ko ? `${10 - today.length}명 더 모이면 5:5 편성 가능` : `${10 - today.length} more for 5v5`) : (ko ? '5:5 편성을 시작할 수 있습니다' : 'Ready for a 5v5 lineup')}</p></div>
    </section>
    <section className="club-metrics" aria-label={ko ? '운영 현황' : 'Club overview'}>{[
      [Users, t('registered'), players.length, ko ? '함께하는 선수' : 'Club players'],
      [Trophy, ko ? '완료한 내전' : 'Completed matches', completed.length, ko ? 'DB에 저장된 경기' : 'Matches in the database'],
      [Clock3, ko ? '진행·입력 대기' : 'Pending results', pending.length, ko ? '결과를 남겨주세요' : 'Awaiting results'],
      [Activity, ko ? '저장된 팀' : 'Saved teams', data.teams.length, ko ? '다음 대회에 사용' : 'Ready for tournaments'],
    ].map(([Icon, label, value, hint], index) => { const Symbol = Icon as typeof Users; return <article key={index}><Symbol size={20} /><span>{String(label)}</span><strong>{loading ? '—' : String(value)}</strong><small>{String(hint)}</small></article>; })}</section>
    <section className="home-grid"><article className="panel"><div className="panel-head"><div><p className="eyebrow">TODAY’S ROSTER</p><h2>{ko ? '오늘 함께할 선수' : 'Today’s roster'}</h2></div><NavLink className="text-link" to="/players">{ko ? '참가 관리' : 'Manage'} →</NavLink></div><div className="today-roster">{today.slice(0, 10).map(p => <div key={p.id}><span className="player-avatar">{p.displayName.slice(0, 1)}</span><div><strong>{p.displayName}</strong><small>{p.positions.join(' · ')}</small></div><b>{data.ratings[p.id] ? Math.round(data.ratings[p.id]!.overallScore) : p.inhouseTier}</b></div>)}</div>{!today.length && <div className="onboarding-empty"><Users size={30} /><strong>{ko ? '오늘 참가할 선수를 선택하세요' : 'Choose today’s players'}</strong><p>{ko ? '선수 목록에서 오늘 참가 스위치를 켜면 여기에 모입니다.' : 'Toggle attendance in the player roster.'}</p><NavLink className="button secondary" to="/players">{ko ? '선수 목록 열기' : 'Open player roster'}</NavLink></div>}</article>
      <article className="panel"><div className="panel-head"><div><p className="eyebrow">MATCH LOG</p><h2>{t('recentMatches')}</h2></div><NavLink className="text-link" to="/history">{ko ? '전체 기록' : 'All matches'} →</NavLink></div><div className="home-match-list">{data.matches.slice(0, 5).map(m => <NavLink key={m.id} to="/history"><span className={`match-marker ${m.status === 'COMPLETED' ? 'completed' : ''}`}><CalendarPlus size={17} /></span><div><strong>{m.event?.name || 'Inhouse'}</strong><small>{formatDate(m.createdAt, language)}</small></div><b>{m.status === 'COMPLETED' ? m.winnerTeam ? `${m.winnerTeam} WIN` : (ko ? '결과 확인 필요' : 'Check result') : t(m.status === 'IN_PROGRESS' ? 'inProgress' : m.status === 'CANCELLED' ? 'cancelled' : 'ready')}</b><ArrowRight size={14} /></NavLink>)}</div>{!data.matches.length && <div className="onboarding-empty"><CalendarPlus size={30} /><strong>{ko ? '첫 내전을 시작해 보세요' : 'Start your first match'}</strong><p>{ko ? '팀을 편성하고 저장하면 경기 기록을 남길 수 있습니다.' : 'Build teams and save the match to start recording.'}</p></div>}</article></section>
    <section className="operation-path">{[['01', '/players', ko ? '참가자 확인' : 'Choose players', ko ? '오늘 참가와 가능 포지션' : 'Attendance and roles'], ['02', '/builder', ko ? '균형 팀 편성' : 'Balance teams', ko ? '포지션별 전력과 수동 조정' : 'Role scores and adjustments'], ['03', '/history', ko ? '경기 결과 기록' : 'Save match results', ko ? '승패와 개인 경기 지표' : 'Outcome and player stats'], ['04', '/stats', ko ? '다음 경기 준비' : 'Prepare the next game', ko ? '쌓인 기록과 개인 통계' : 'Player history and statistics']].map(([number, path, title, description]) => <NavLink key={number} to={path!}><span>{number}</span><div><strong>{title}</strong><small>{description}</small></div><ArrowRight size={15} /></NavLink>)}</section>
    <div className="service-strip"><span className={`service-chip ${ready ? 'ready' : ''}`}>{ready ? (ko ? '중앙 DB 연결됨' : 'Database connected') : (ko ? 'DB 연결 확인 필요' : 'Check database connection')}</span><span>{data.health?.riotConfigured ? (ko ? 'Riot 키 설정됨' : 'Riot key configured') : (ko ? 'Riot 키 연결 대기' : 'Awaiting Riot key')}</span><span>{ko ? '내전 결과: 수동 기록 · 자동 수집 준비 중' : 'Manual match results · automation pending'}</span><NavLink to="/settings">{ko ? '연결 상태 보기' : 'View connections'} →</NavLink></div>
  </>;
}
