import { useEffect, useState } from 'react';
import { api } from '../lib/api';
interface Session {code:string|null;state:string;riotMatchId:string|null;lastErrorCode:string|null}
export function TournamentCollection({matchId,onCollected}:{matchId:string;onCollected:()=>Promise<void>}) {
 const [session,setSession]=useState<Session|null>(null);const [consent,setConsent]=useState(false);const [busy,setBusy]=useState(false);const [error,setError]=useState('');
 useEffect(()=>{let active=true;let wasComplete=false;async function load(){try{const result=await api.tournamentSession(matchId);if(active){setSession(result.session);if(result.session?.state==='COMPLETE'&&!wasComplete){wasComplete=true;await onCollected();}}}catch(e){if(active)setError(e instanceof Error?e.message:'자동 수집 연결 확인 실패');}}void load();const timer=setInterval(()=>void load(),15000);return()=>{active=false;clearInterval(timer);};},[matchId,onCollected]);
 async function run(retry:boolean){setBusy(true);setError('');try{await api.prepareTournament(matchId,retry?{action:'retry'}:{consentConfirmed:consent});setSession((await api.tournamentSession(matchId)).session);await onCollected();}catch(e){setError(e instanceof Error?e.message:'자동 수집 요청 실패');}finally{setBusy(false);}}
 const labels:Record<string,string>={CREATING:'코드 생성 중',WAITING:'경기 종료 대기',RECEIVED:'결과 확인 중',RETRY:'수집 재시도 필요',COMPLETE:'자동 저장 완료',UNKNOWN:'발급 상태 확인 필요'};
 return <div className="collection-panel"><strong>내전 자동 수집</strong><p className="helper">발급 코드로 로비에 입장해 경기하면 종료 후 결과를 중앙 DB에 저장합니다. 일반 사용자 설정 로비는 이 수집 경로에 연결되지 않습니다.</p>{session?<><p>{labels[session.state]??session.state}</p>{session.code&&<><code>{session.code}</code><button className="button secondary" onClick={()=>{void navigator.clipboard.writeText(session.code!).catch(()=>setError('코드를 직접 선택해 복사하세요.'));}}>코드 복사</button></>}{session.state==='RETRY'&&<button className="button primary" disabled={busy} onClick={()=>void run(true)}>결과 다시 수집</button>}{session.lastErrorCode&&<p className="helper">운영 확인 코드: {session.lastErrorCode}</p>}</>:<><label className="field"><span><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/> 참가자 10명에게 LoL 내전 기록의 수집·공유 동의를 확인했습니다.</span></label><button className="button primary" disabled={busy||!consent} onClick={()=>void run(false)}>{busy?'요청 중…':'Tournament 코드 발급'}</button></>}{error&&<p className="form-error" role="alert">{error}</p>}<p className="helper">Production 및 Tournament 권한 승인·서버 연결 후 사용 가능합니다. 상태를 확인하지 못한 발급 요청은 중복 발급하지 않으며 운영자가 확인합니다.</p></div>;
}
